### ISSUE TITLE
Fix FAT File Structure So That iOS Simulator Works Again

### ISSUE THREAD

**Issue by bobkressin** [kstechnologies/NIRScanNano_iOS#4]

**Comment by Seoras** [comment]
It appears that the iOS Simulator is once again working without any changes required to the KST framework library for TI's Nano.
Sagitto's App now compiles and runs on both iPhone and iPad simulators on Xcode 10.2.1
You might want to re-test your demo app and close off this issue.

**Comment by bobkressin** [comment]
Great to hear, @Seoras . Please let us know if we can help in any other way.
